parserOptions:
  ecmaVersion: 2020

rules:
  no-underscore-dangle: 
    - 2
    - allow:
        - "__filename"
        - "__dirname"
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  import/no-duplicates: off

plugins:
  - jest

env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
